### ISSUE TITLE
sync tags into obsidian format

### ISSUE THREAD

**Issue by yy4382** [huseyz/obsidian-wallabag#13]
Hello!

I have read the documentation and noticed that it only allows exporting tags separated by commas. Could you consider adding an option to convert tags from wallabag into obsidian format? 
For example, if an article in wallabag has tags "foo" and "bar," I would like them to be converted into #foo #bar tags when syncing to obsidian.

I would greatly appreciate it if this feature could be implemented.

**Comment by huseyz** [comment]
This is indeed fairly simple to implement since we're already syncing the tags and it sounds like a good idea. I will give it a shot when I have sometime

**Comment by yy4382** [comment]
Looking forward  to it : )

**Comment by chymian** [comment]
@huseyz 
any news on that? 
checked on 0.1.4, still substituting with a comma-seperated list
IMHO:
that's a kind of a showstopper, since Obsidian/Logseq family of apps are heavily based on tagging to build/sort/access/query the Graph.
importing hundreds+  articles without propper tagging seems somehow counterproductive.

**Comment by huseyz** [comment]
It is a valid point. 
I use frontmatter to tag all my documents, hence the current implementation.

I'm reopening this because I want to implement this as an option.

**Comment by huseyz** [comment]
Implemented this as an option; will create a release now.
