### ISSUE TITLE
Youtube Videos

### ISSUE THREAD

**Issue by rubenssoto** [huseyz/obsidian-wallabag#35]
Hi, how are you?

Thank you so much for this amazing plugin. When I tried to sync youtube videos that plugin is getting the wrong yt url.

For example: https://www.youtube.com/oembed?format=xml&url=https://www.youtube.com/watch?v%3DT2r1jyhT2vg

Is there any way to solve this? thank you

**Comment by huseyz** [comment]
Hi @rubenssoto, thanks for the issue. 
When you bag a YouTube video, Wallabag uses the embed link as its URL. API also returns a origin link; storing the direct video link.
We should expose this field as a new template variable, something like `{{origin_link}}`, so you can use it in your template. I will give it a go in the coming few days.

**Comment by huseyz** [comment]
Published https://github.com/huseyz/obsidian-wallabag/releases/tag/0.3.2 with the fix.

Please update and use `{{given_url}}` instead of `{{original_link}}` in your template. 
As a side note, this issue only happens when you bag a video directly using the wallabag web interface, when I use the Firefox plugin it's all fine.

**Comment by rubenssoto** [comment]
@huseyz thank you so much
