### ISSUE TITLE
Feature Request: Dealing with False Duplicates

### ISSUE THREAD

**Issue by mwsmedia** [huseyz/obsidian-wallabag#6]
It looks like the plugin automatically marks a duplicate if the title pulled from Wallabag is the same as a previous article... however, Tumblr articles apparently often appear to have the title of the Tumblr blog as the title of the article... leading to false positive duplicate detection.

Is it possible to either set a toggle to include duplicates or, possibly, customize the way the plugin detects duplicates (ie, same source URL, perhaps, or same publication date, not same title?)

Thanks so much for the work you've done on this.

**Comment by huseyz** [comment]
This is an interesting edge case I haven't thought about. 
Title based duplicate detection happens because Obsidian doesn't allow duplicate filenames. Plugin actually keeps track of the Wallabag IDs for duplicate detection, meaning we can just append the title with that ID when there is a conflict, hacky solution but it would work.
I'm gonna publish a fix as soon as possible.

**Comment by huseyz** [comment]
Changed my mind on the method, added a new option to include the article ID in the file titles, a bit ugly but should solve your problem.
New release: https://github.com/huseyz/obsidian-wallabag/releases/tag/v0.1.2
